#define TRIGGER_PIN_LEFT 13
#define TRIGGER_PIN_RIGHT 12

#define ECHO_PIN_LEFT 4
#define ECHO_PIN_RIGHT 3

#define START_BTN_PIN 2
#define DEBOUNCE_DELAY 200

#define LEFT_MOTOR_POS 6
#define LEFT_MOTOR_GND 9

#define RIGHT_MOTOR_POS 10
#define RIGHT_MOTOR_GND 11

#define SPEED_OF_SOUND 0.0343
#define STOPPING_DISTANCE 10

#define MAX_DISTANCE_DEVIATION 0.1
#define PARKING_COOLDOWN 2000